=== Dj3ni/Appli-XML/exercices/exe_DTD/exeLivreDTD.dtd
<!ELEMENT livres (livre+)>

<!ELEMENT livre (title, publicationDate, type, author)>
<!-- We use CDATA because if differents series, there can be 5 book 1 etc so no Id!-->
<!ATTLIST livre series-name CDATA #IMPLIED>
<!ATTLIST livre tome CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT publicationDate (#PCDATA)>
<!-- It does'nt understand "/" so we have to tell it what it must accept -->
<!ATTLIST publicationDate format NOTATION (dmyFrench | year) #REQUIRED>
<!NOTATION dmyFrench PUBLIC "dd-mm-yyyy">
<!NOTATION year PUBLIC "yyyy">

<!ELEMENT type (#PCDATA)>

<!ELEMENT author (firstname,name)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== Dj3ni/Appli-XML/exercices/exe_DTD/exeLivre.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<!DOCTYPE livres SYSTEM "./exeLivreDTD.dtd">

<livres>
    <livre series-name="Harry Potter" tome="1">
        <title>Harry Potter à l'école des Sorciers</title>
        <publicationDate format="dd-mm-yyyy">20-08-2024</publicationDate>
        <type>fantasy</type>
        <author>
            <firstname>J.K</firstname>
            <name>Rowling</name>
        </author>
    </livre>
    <livre>
        <title>Léon le Moucheron</title>
            <publicationDate format="dd-mm-yyyy">20-08-2024</publicationDate>
            <type>Enfance</type>
            <author>
                <firstname>Samuel</firstname>
                <name>Legrain</name>
            </author>
    </livre>
</livres>
