=== Dj3ni/Appli-XML/exercices/revisions/exe1.dtd
<!ELEMENT livres (livre+)>
<!ELEMENT livre (titre, auteur+, editeur, prix, datePublication)>
<!ATTLIST livre series-name CDATA #IMPLIED>
<!ATTLIST livre tome CDATA #IMPLIED>

<!ELEMENT auteur (noms)>
<!ELEMENT noms (prenom, nom)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

<!ELEMENT editeur (#PCDATA)>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT prix (#PCDATA)>

<!ELEMENT datePublication (#PCDATA)>
<!ATTLIST datePublication format NOTATION (dmyFrench|year) #REQUIRED>
<!NOTATION dmyFrench PUBLIC "dd/mm/yyyy">
<!NOTATION year PUBLIC "yyyy">

=== Dj3ni/Appli-XML/exercices/revisions/exe1.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<!-- <!DOCTYPE livres SYSTEM "./exe1.dtd"> -->

<livres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./exe1.xsd">

    <livre series-name ="Harry Potter" tome ="1">
        <titre>Harry Potter à l'école des sorciers</titre>
        <auteur>
            <noms>
                <prenom>J.K.</prenom>
                <nom>Rowling</nom>
            </noms>
        </auteur>
        <editeur>Gallimard</editeur>
        <prix>25.00</prix>
        <datePublication format="year">2000</datePublication>
    </livre>
    <livre series-name ="Harry Potter" tome ="2">
        <titre>Harry Potter et la chambre des secrets</titre>
        <auteur>
            <noms>
                <prenom>J.K.</prenom>
                <nom>Rowling</nom>
            </noms>
        </auteur>
        <editeur>Gallimard</editeur>
        <prix>25.00</prix>
        <datePublication format="year">2002</datePublication>
    </livre>

</livres>
